### ISSUE TITLE
Please add License

### ISSUE THREAD

**Issue by klahnakoski** [danielmoniz/merge_in_memory#2]
Hi!  I am from Mozilla, and I would like permission to use your code in my current project (https://github.com/klahnakoski/Bugzilla-ETL).   Mozilla's Bugzilla instance has recently been changed to store diffs of user stories in bug history (https://bugzilla.mozilla.org/show_bug.cgi?id=895687).  I need to rebuild the history of the user story from those diffs.

Github licensing defaults to All-Rights-Reserved.  If you intended your code to be open source, please add an explicit license to your repo (or in header of source files)

Thank you!  Happy programming!

**Comment by Permafacture** [comment]
+1  Please fix this.

http://choosealicense.com/

**Comment by danielmoniz** [comment]
I've chosen the MIT license. Thanks for the nudge on this!

**Comment by Permafacture** [comment]
Great.   You might want to put your actual name and year in there, rather
than [name] [year]

**Comment by danielmoniz** [comment]
_sigh_ Thanks, I was in a hurry! Fixed.
